
FROM python:3.12-alpine
WORKDIR /app
COPY requirements.txt .
# Устанавливаем глобально, не в --user
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
ENV APP_VERSION=2.0
# Создаем пользователя и даем права на /app
RUN adduser -D appuser && \
    chown -R appuser:appuser /app
USER appuser
EXPOSE 5000
CMD ["python", "app.py"]
