apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "env | grep -E 'APP|LOG|MAX|MY_ENV'; cat /etc/config/nginx.conf; sleep 3600"]

      envFrom:
        - configMapRef:
            name: app-config

      env:
        - name: MY_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

      volumeMounts:
        - name: config-volume
          mountPath: /etc/config

  volumes:
    - name: config-volume
      configMap:
        name: nginx-conf
