apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "env | grep -E 'APP|LOG|MAX'; cat /etc/config/nginx.conf; sleep 3600"]
      # Способ 1: все ключи как переменные окружения
      envFrom:
        - configMapRef:
            name: app-config

      # Способ 2: конкретный ключ под своим именем
      env:
        - name: MY_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV

      # Способ 3: смонтировать как файл
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: nginx-conf # Убедись, что имя ConfigMap совпадает с созданным