apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "env | grep -E 'APP|LOG|MAX'; cat /etc/config/nginx.conf; sleep 3600"]

    # Способ 1: все ключи как переменные окружения
    envFrom:
    - configMapRef:
        name: app-config
        
  volumes:
  - name: config-volume
    configMap:
      name: nginx-conf